export const avatarList = [
  {
    category: 'Bayi',
    items: [
      '/images/avatar/BAYİ AVATAR ERKEK 1.svg',
      '/images/avatar/BAYİ AVATAR ERKEK 2.svg',
      '/images/avatar/BAYİ AVATAR ERKEK 3.svg',
      '/images/avatar/BAYİ AVATAR ERKEK 4.svg',
      '/images/avatar/BAYİ AVATAR ERKEK 5.svg',
      '/images/avatar/BAYİ AVATAR ERKEK 6.svg',
      '/images/avatar/BAYİ AVATAR KADIN 1.svg',
      '/images/avatar/BAYİ AVATAR KADIN 2.svg',
      '/images/avatar/BAYİ AVATAR KADIN 3.svg',
      '/images/avatar/BAYİ AVATAR KADIN 4.svg',
      '/images/avatar/BAYİ AVATAR KADIN 5.svg',
      '/images/avatar/BAYİ AVATAR KADIN 6.svg',
    ],
  },
  {
    category: 'Erkek',
    items: [
      '/images/avatar/AVATAR ERKEK 1.svg',
      '/images/avatar/AVATAR ERKEK 2.svg',
      '/images/avatar/AVATAR ERKEK 3.svg',
      '/images/avatar/AVATAR ERKEK 4.svg',
      '/images/avatar/AVATAR ERKEK 5.svg',
      '/images/avatar/AVATAR ERKEK 6.svg',
      '/images/avatar/AVATAR ERKEK 8.svg',
      '/images/avatar/AVATAR ERKEK 9.svg',
      '/images/avatar/AVATAR ERKEK 10.svg',
      '/images/avatar/AVATAR ERKEK 11.svg',
      '/images/avatar/AVATAR ERKEK 12.svg',
    ],
  },
  {
    category: 'Kadın',
    items: [
      '/images/avatar/AVATAR KADIN 1.svg',
      '/images/avatar/AVATAR KADIN 2.svg',
      '/images/avatar/AVATAR KADIN 3.svg',
      '/images/avatar/AVATAR KADIN 4.svg',
      '/images/avatar/AVATAR KADIN 6.svg',
      '/images/avatar/AVATAR KADIN 7.svg',
      '/images/avatar/AVATAR KADIN 8.svg',
      '/images/avatar/AVATAR KADIN 9.svg',
      '/images/avatar/AVATAR KADIN 10.svg',
      '/images/avatar/KADIN2.svg',
    ],
  },
  {
    category: 'Hayvanlar',
    items: [
      '/images/avatar/CAT.svg',
      '/images/avatar/DOG.svg',
      '/images/avatar/ELEPHANT.svg',
      '/images/avatar/FROG.svg',
      '/images/avatar/KOALA.svg',
      '/images/avatar/LİON.svg',
      '/images/avatar/MONKEY.svg',
      '/images/avatar/PANDA.svg',
      '/images/avatar/SHEEP.svg',
      '/images/avatar/TİGER.svg',
      '/images/avatar/ZÜRAFA.svg',
    ],
  },
  {
    category: 'Meyveler',
    items: [
      '/images/avatar/APPLE.svg',
      '/images/avatar/AVACADO.svg',
      '/images/avatar/BANANA.svg',
      '/images/avatar/BLUEBERRY.svg',
      '/images/avatar/CHERRRY.svg',
      '/images/avatar/DRAGON FRUİT.svg',
      '/images/avatar/GRAPE.svg',
      '/images/avatar/ORANGE.svg',
      '/images/avatar/STRAWBERRY.svg',
      '/images/avatar/WATERMELON.svg',
    ],
  },
  {
    category: 'Yiyecekler',
    items: [
      '/images/avatar/COFFFE.svg',
      '/images/avatar/DONUT.svg',
      '/images/avatar/DRİNKS.svg',
      '/images/avatar/FRİES.svg',
      '/images/avatar/HAMBURGER.svg',
      '/images/avatar/İCE CREAM.svg',
      '/images/avatar/PİZZ.svg',
    ],
  },
  {
    category: 'Emojiler',
    items: [
      '/images/avatar/EMOJİ1.svg',
      '/images/avatar/EMOJİ2.svg',
      '/images/avatar/EMOJİ3.svg',
      '/images/avatar/EMOJİ4.svg',
      '/images/avatar/EMOJİ5.svg',
      '/images/avatar/EMOJİ6.svg',
      '/images/avatar/EMOJİ7.svg',
      '/images/avatar/EMOJİ8.svg',
    ],
  },
  {
    category: 'Diğer',
    items: ['/images/avatar/CPW.svg'],
  },
] as const;

export const defaultAvatars = avatarList.flatMap((category) => category.items);
